version: "3.8"
services:

  #php-fpm
  php-fpm:
    build:
      context: ./php/
      dockerfile: Dockerfile
    container_name: ${APP_NAME}-php
    restart: on-failure
    tty: true
    volumes:
      - ./:/var/www/
    networks:
      - common

  #nginx
  nginx:
    image: nginx:latest
    container_name: ${APP_NAME}-nginx
    restart: on-failure
    tty: true
    ports:
      - '80:80'
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - common

  #database
  postgres:
      image: postgres:latest
      container_name: ${APP_NAME}-postgres
      restart: always
      tty: true
      ports:
          - "5432:5432"
      environment:
          POSTGRES_DB: postgres
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD:
      volumes:
          - database:/var/lib/postgresql/data
      networks:
          - common

networks:
  common:
    driver: bridge

volumes:
 database:
  name: ${APP_NAME}-${DB_CONNECTION}